DAPP-394 & DAPP-393: Transactions Table Tests
Topl/faucet pull request #28
Opened 2023-11-07 20:01 UTC by lukorito

## Description

Add tests for transactions table for desktop, table and mobile
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
 make file_test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added screenshots

2023-11-08 15:13 UTC, KalervoHyyppa requested changes
One super small request

2023-11-08 15:13 UTC, KalervoHyyppa commented on lib/transactions/widgets/paginated_transaction_table.dart
> +    print("called");
Clean Up

2023-11-08 22:54 UTC, lukorito commented on lib/transactions/widgets/paginated_transaction_table.dart
> +    print("called");
Sorted @KalervoHyyppa

2023-11-09 14:40 UTC, KalervoHyyppa approved these changes
lgtm

2023-11-09 21:38 UTC, merged